package com.example.sergeyv.weatherapp.model;

/**
 * Created by sergeyv on 23/10/2017.
 */

public final class CountryCodes {
    public static final String[] COUNTRY_CODES = {"AF","AX","AL","DZ","AS","AD","AO","AI","AG","AR",
            "AM","AW","AU","AT","AZ","BS","BH","BD","BB","BY",
            "BE","BZ","BJ","BM","BT","BO","BA","BW","BR","VG",
            "BN","BG","BF","BI","KH","CM","CA","CV","KY","CF",
            "TD","CL","CN","HK","MO","CX","CC","CO","KM","CG",
            "CD","CK","CR","CI","HR","CU","CY","CZ","DK","DJ",
            "DM","DO","EC","EG","SV","GQ","ER","EE","ET","FK",
            "FO","FJ","FI","FR","GF","PF","TF","GA","GM","GE",
            "DE","GH","GI","GR","GL","GD","GP","GU","GT","GG",
            "GN","GW","GY","HT","VA","HN","HU","IS","IN","ID",
            "IR","IQ","IE","IM","IL","IT","JM","JP","JE","JO",
            "KZ","KE","KI","KP","KR","KW","KG","LA","LV","LB",
            "LS","LR","LY","LI","LT","LU","MK","MG","MW","MY",
            "MV","ML","MT","MH","MQ","MR","MU","YT","MX","FM",
            "MD","MC","MN","ME","MS","MA","MZ","MM","NR","NP",
            "NL","NC","NZ","NI","NE","NG","NU","NF","MP","NO",
            "OM","PK","PW","PS","PA","PG","PY","PE","PH","PN",
            "PL","PT","PR","QA","RE","RO","RU","RW","BL","SH",
            "KN","LC","MF","PM","VC","WS","SM","ST","SA","SN",
            "RS","SC","SL","SG","SK","SI","SB","SO","ZA","GS",
            "SS","ES","LK","SD","SR","SJ","SZ","SE","CH","SY",
            "TW","TJ","TZ","TH","TL","TG","TO","TT","TN","TR",
            "TM","TC","TV","UG","UA","AE","GB","US","UY","UZ",
            "VU","VE","VN","VI","WF","EH","YE","ZM","ZW","NA",
            "XK"};
    public static final String[] COUNTRY_NAMES = {"Afghanistan","Aland Islands","Albania","Algeria","American Samoa","Andorra",
            "Angola","Anguilla","Antigua and Barbuda","Argentina","Armenia","Aruba",
            "Australia","Austria","Azerbaijan","Bahamas","Bahrain","Bangladesh",
            "Barbados","Belarus","Belgium","Belize","Benin","Bermuda",
            "Bhutan","Bolivia","Bosnia and Herzegovina","Botswana","Brazil","British Virgin Islands",
            "Brunei Darussalam","Bulgaria","Burkina Faso","Burundi","Cambodia","Cameroon",
            "Canada","Cape Verde","Cayman Islands","Central African Republic","Chad","Chile",
            "China","Hong Kong, SAR China","Macao, SAR China","Christmas Island","Cocos (Keeling) Islands","Colombia",
            "Comoros","Congo (Brazzaville)","Congo, (Kinshasa)","Cook Islands","Costa Rica","Côte d'Ivoire",
            "Croatia","Cuba","Cyprus","Czech Republic","Denmark","Djibouti",
            "Dominica","Dominican Republic","Ecuador","Egypt","El Salvador","Equatorial Guinea",
            "Eritrea","Estonia","Ethiopia","Falkland Islands (Malvinas)","Faroe Islands","Fiji",
            "Finland","France","French Guiana","French Polynesia","French Southern Territories","Gabon",
            "Gambia","Georgia","Germany","Ghana","Gibraltar","Greece",
            "Greenland","Grenada","Guadeloupe","Guam","Guatemala","Guernsey",
            "Guinea","Guinea-Bissau","Guyana","Haiti","Holy See (Vatican City State)","Honduras",
            "Hungary","Iceland","India","Indonesia","Iran, Islamic Republic of","Iraq",
            "Ireland","Isle of Man","Israel","Italy","Jamaica","Japan",
            "Jersey","Jordan","Kazakhstan","Kenya","Kiribati","Korea (North)",
            "Korea (South)","Kuwait","Kyrgyzstan","Lao PDR","Latvia","Lebanon",
            "Lesotho","Liberia","Libya","Liechtenstein","Lithuania","Luxembourg",
            "Macedonia, Republic of","Madagascar","Malawi","Malaysia","Maldives","Mali",
            "Malta","Marshall Islands","Martinique","Mauritania","Mauritius","Mayotte",
            "Mexico","Micronesia, Federated States of","Moldova","Monaco","Mongolia","Montenegro",
            "Montserrat","Morocco","Mozambique","Myanmar","Nauru","Nepal",
            "Netherlands","New Caledonia","New Zealand","Nicaragua","Niger","Nigeria",
            "Niue","Norfolk Island","Northern Mariana Islands","Norway","Oman","Pakistan",
            "Palau","Palestinian Territory","Panama","Papua New Guinea","Paraguay","Peru",
            "Philippines","Pitcairn","Poland","Portugal","Puerto Rico","Qatar",
            "Réunion","Romania","Russian Federation","Rwanda","Saint-Barthélemy","Saint Helena",
            "Saint Kitts and Nevis","Saint Lucia","Saint-Martin (French part)","Saint Pierre and Miquelon","Saint Vincent and Grenadines","Samoa",
            "San Marino","Sao Tome and Principe","Saudi Arabia","Senegal","Serbia","Seychelles",
            "Sierra Leone","Singapore","Slovakia","Slovenia","Solomon Islands","Somalia",
            "South Africa","South Georgia and the South Sandwich Islands","South Sudan","Spain","Sri Lanka","Sudan",
            "Suriname","Svalbard and Jan Mayen Islands","Swaziland","Sweden","Switzerland","Syrian Arab Republic (Syria)",
            "Taiwan, Republic of China","Tajikistan","Tanzania, United Republic of","Thailand","Timor-Leste","Togo",
            "Tonga","Trinidad and Tobago","Tunisia","Turkey","Turkmenistan","Turks and Caicos Islands",
            "Tuvalu","Uganda","Ukraine","United Arab Emirates","United Kingdom","United States of America",
            "Uruguay","Uzbekistan","Vanuatu","Venezuela (Bolivarian Republic)","Viet Nam","Virgin Islands, US",
            "Wallis and Futuna Islands","Western Sahara","Yemen","Zambia","Zimbabwe","Namibia","Kosovo"};
}
